path:
  base_data_dir: /home/molra/workspace/3d_number/data
  train_serial: 20220924164251
  pred_cv: 0

data:
  test_make_select: True
  num_workers: 8

predict:
  batch_size: 16

other:
  random_seed: 42
  train_val_predict: False

